server:
  port: 8081
  # 资源压缩传输
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
    - text/html
    - text/xml
    - text/plain
    - text/css
    - text/javascript
    - application/javascript
    - application/json
    - application/xml
    - image/gif
    - image/jpeg
    - image/png
# 日志（默认行为是一天一个日志文件）
logging:
  # 按照spring规范要求，单独指定一个logback的配置文件
#  config: classpath:logback-spring.xml
  # 日志输出级别
#  level:
#    root: debug
#    web: debug
  # 文件策略：文件名、压缩（默认每天压缩一个）
#  file:
    # 完整文件名
#    name: wmc.log
    # 超过这个大小，将被压缩
#    max-size: 10MB
    # 日志最大保存天数
#    max-history: 7
  # 日志格式
  pattern:
    # 指定时间格式
    dateformat: yyyy-MM-dd HH:mm:ss
    # 指定输出到控制台的日志格式
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%15.15t] %-40.40c{1.} [%X{user}] : %m%n%xwEx"

spring:
#   # springboot的异步，是基于jdk的动态代理实现的，即基于接口，那么编写的类就不能使用接口了，所以修改默认的动态代理策略为CGLIB，即基于类，也可以在@EnableAsync注解上配置
#  aop:
#    proxy-target-class: true
  pid:
    file: application.pid
  # 企业微信邮箱服务器
  mail:
    # SMTP服务器
    host: smtp.exmail.qq.com
    # SMTP服务器秘钥
    password: GfTzFAJ7aEcUqgbx
    # 邮件发送者的真实邮箱
    username: mincong.wang@firstouch.com.cn
    # 添加如下配置，即采用SMTPS协议发送邮件(465端口)，默认是SMTP协议(25端口)
    properties:
      mail:
        smtp:
          port: 465
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

  # 数据源
  datasource:
    url: jdbc:mysql://localhost:8090/springboot?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    hikari:
      # ebean 托管事物提交，这里需要关闭自动提交
      auto-commit: false
      connection-init-sql: select 1
      # 测试数据库连接sql
      connection-test-query: select 1
      # 数据库连接超时时间（默认30秒，单位：毫秒）
      connection-timeout: 30000
      # 最小空闲连接数量（默认：10）
      minimum-idle: 4
      # 连接池最大连接数（默认：10）
      maximum-pool-size: 16
      # 连接的最长生命周期，值0表示无限生命周期（默认：30分钟，单位：毫秒）
      max-lifetime: 600000
      # 空闲连接最大存活时间（默认：10分钟，单位：毫秒）
      idle-timeout: 300000

  # 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# ebean
ebean:
  ddl-generate: true
  ddl-run: false

# 自定义配置
app:
  # 自定义域名
  domain: http://127.0.0.1
  # 是否根据area.json生成对应的sql语句
  area-sql:
    # 是否要生成
    generate: false
    # 是否生成一个整合文件
    single-file: true
  # 异常邮件通知
  exception-mail-notify:
    # 邮件发送者的昵称
    nickname: My Bug Reporter
    # 是否开启发生预期外异常时邮件提示（默认：关闭）
    'on': true
    # 发生预期外异常时，要通知的邮箱
    send-to: mincong.wang@firstouch.com.cn
  # 是否开启swagger
  swagger-enable: true
  # api 文档版本
  api-version: v1.0
