spring:
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:8090/springboot?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    hikari:
      connection-init-sql: select 1
      # 测试数据库连接sql
      connection-test-query: select 1
      # 数据库连接超时时间（默认30秒，单位：毫秒）
      connection-timeout: 30000
      # 最小空闲连接数量（默认：10）
      minimum-idle: 4
      # 连接池最大连接数（默认：10）
      maximum-pool-size: 16
      # 连接的最长生命周期，值0表示无限生命周期（默认：30分钟，单位：毫秒）
      max-lifetime: 600000
      # 空闲连接最大存活时间（默认：10分钟，单位：毫秒）
      idle-timeout: 300000